
tasks:
  - name: Steedos
    command: |
      cd steedos-enterprise
      echo "ROOT_URL=$(gp url 5000)" >> .env
      docker-compose up

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    visibility: public

vscode:
  extensions:
    - cweijan.vscode-mysql-client2