
tasks:
  - name: Steedos
    command: |
      cd steedos-community
      echo "STEEDOS_ROOT_URL=$(gp url 3000)" >> .env
      docker-compose -f docker-compose.yml up

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    visibility: public

vscode:
  extensions:
    - cweijan.vscode-mysql-client2
