
tasks:
  - name: Steedos
    command: |
      echo "STEEDOS_ROOT_URL=$(gp url 3000)" >> steedos-community/.env
      echo "STEEDOS_ROOT_URL=$(gp url 3000)" >> steedos-enterprise/.env
      cd steedos-community
      docker-compose -f docker-compose.yml up

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    visibility: public

vscode:
  extensions:
    - cweijan.vscode-mysql-client2
