version: "3.9"

services:

  steedos:
    image: steedos/steedos-community:2.4
    ports:
      - "3000:3000"
    environment:
      - ROOT_URL=${STEEDOS_ROOT_URL:-http://localhost:3000} 
      - PORT=3000
      - MONGO_URL=mongodb://mongodb:27017/steedos
      - MONGO_OPLOG_URL=mongodb://mongodb:27017/local
      - TRANSPORTER=nats://nats:4222
      - CACHER=redis://redis:6379
      - STEEDOS_INITIAL_PACKAGES=@steedos-labs/project-ee,@steedos-labs/demo-ee,@steedos-labs/flows
    volumes:
      - "steedos-installed-packages:/app/.steedos"
      - "steedos-data:/app/storage"
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 60s
      timeout: 10s
      retries: 3
    depends_on:
      redis:
        condition: service_started
      mongodb:
        condition: service_healthy
        
  redis:
    image: redis:6.2
    command: "redis-server --save \"\" --appendonly no --loglevel warning"
    ports:
      - "6379:6379"
  
  mongodb:
    image: mongo:4.4
    restart: on-failure
    ports:
      - 27017:27017
    command: "--bind_ip_all --replSet steedos --logpath /var/log/mongodb/mongod.log"
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo --quiet | grep 1
      interval: 10s
      timeout: 10s
      retries: 5
    volumes:
      - 'steedos-mongo-data:/data/db'

  mongodb-init:
    image: mongo:4.4
    restart: "no"
    depends_on:
      mongodb:
        condition: service_healthy
    command: >
      mongo --host mongodb:27017 --eval "rs.initiate({ _id: 'steedos', members: [{_id: 0, host: 'mongodb:27017'}]})"

  # Micro Service Transporter
  nats:
    image: nats:2.9
    ports:
      - "4222:4222"
      # - "8222:8222" # monitor port


  # watchtower:
  #   restart: always
  #   image: containrrr/watchtower
  #   ports:
  #     - 8080:8080
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
  #     - /etc/localtime:/etc/localtime:ro
  #   environment:
  #     - WATCHTOWER_CLEANUP=true
  #     - WATCHTOWER_DEBUG=true
  #     - WATCHTOWER_LABEL_ENABLE=true
  #     - WATCHTOWER_SCHEDULE=0 0 1 * * *  # 每天1点定时检查更新，请确认当前时区，自定义调度规则


volumes:
  steedos-mongo-data:
  steedos-installed-packages:
  steedos-data:
