name: Build and push steedos/steedos-enterprise

on:
  push:
    tags:
     - 'v2.2.*'
jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Get branch names
        id: branch-name
        uses: tj-actions/branch-names@v5.2
        with: 
          strip_tag_prefix: v

      - name: Get the current tag
        if: steps.branch-name.outputs.is_tag == 'true'  # Replaces: startsWith(github.ref, 'refs/tags/')
        run: |
          echo "${{ steps.branch-name.outputs.tag }}"

      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
        with:
          driver-opts: network=host
          
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            steedos/steedos-enterprise
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=schedule
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}

      - uses: docker/login-action@v1
        name: Login Docker Hub
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Replace Version ~2.2 to Tag
        if: ${{ startsWith(steps.branch-name.outputs.tag, '2.2') }}
        uses: jacobtomlinson/gha-find-replace@v2
        with:
          include: steedos-enterprise/2.2/package.json
          find: "~2.2"
          replace: ${{steps.branch-name.outputs.tag}}
          regex: false

      - name: Build and push 2.2
        if: ${{ startsWith(steps.branch-name.outputs.tag, '2.2') }}
        uses: docker/build-push-action@v3
        with:
          context: ./steedos-enterprise/2.2
          platforms: linux/amd64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Replace Version ~2.3 to Tag
        if: ${{ startsWith(steps.branch-name.outputs.tag, '2.3') }}
        uses: jacobtomlinson/gha-find-replace@v2
        with:
          include: steedos-enterprise/2.3/package.json
          find: "~2.3"
          replace: ${{steps.branch-name.outputs.tag}}
          regex: false

      - name: Build and push 2.3
        if: ${{ startsWith(steps.branch-name.outputs.tag, '2.3') }}
        uses: docker/build-push-action@v3
        with:
          context: ./steedos-enterprise/2.3
          platforms: linux/amd64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
